version: '3.8'

name: my_portfolio

services:
  nodejs:
    container_name: my_portfolio_nodejs
    build:
      context: .
      args:
        - NODE_VERSION=22.11.0
    volumes:
      - './:/home/app'
    # expose:
    #   - "3000"
    ports:
      - "3001:3000"
    networks:
      - my_portfolio_net
networks:
  my_portfolio_net:
    name: my_portfolio_net_name
    driver: bridge
    
